In [2]:
# Exercise 1
category = "Misinformation about turtles"
age = 19
engagement_rate = 0.672

print(category)
print(age)
print(engagement_rate)

print(type(category))
print(type(age))
print(type(engagement_rate))

Misinformation about turtles
19
0.672
<class 'str'>
<class 'int'>
<class 'float'>


In [3]:
# Exercise 2
category = {"topic": "Turtle conspiracy", "believers": "Too many"}

print(category)
print(type(category))

{'topic': 'Turtle conspiracy', 'believers': 'Too many'}
<class 'dict'>


In [4]:
# Exercise 2 continued
rickroll = """Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you"""

print(rickroll)

Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you


Double click and enter answer here: Unstructured data.

In [5]:
# Exercise 3
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.2.2
2.0.2


In [6]:
# Exercise 4
ages = np.array([22, 34, 18, 27, 45])
engagement_rates = np.array([0.25, 0.76, 0.58, 0.91, 0.47])
users = np.array(["Alex", "Jamie", "Morgan", "Taylor", "Jordan"])

print(ages)
print(engagement_rates)
print(users)

[22 34 18 27 45]
[0.25 0.76 0.58 0.91 0.47]
['Alex' 'Jamie' 'Morgan' 'Taylor' 'Jordan']


In [7]:
# Exercise 4 continued
print(users[2])
print(np.sum(ages))
print(np.mean(engagement_rates))

Morgan
146
0.594


In [8]:
# Exercise 4 continued
users[0] = "Gizmo"
ages[-1] = 50

print(users)
print(ages)


['Gizmo' 'Jamie' 'Morgan' 'Taylor' 'Jordan']
[22 34 18 27 50]


In [9]:
# Exercise 5
df = pd.DataFrame({
    "Name": users,
    "Age": ages,
    "Engagement": engagement_rates
})

print(df)

     Name  Age  Engagement
0   Gizmo   22        0.25
1   Jamie   34        0.76
2  Morgan   18        0.58
3  Taylor   27        0.91
4  Jordan   50        0.47


Double click and enter answer here: Structured.

In [10]:
# Exercise 5 continued
print(df['Age'].mean())
print(df['Engagement'].mean())
print(df['Engagement'].median())
print(df['Engagement'].mode())
print(df['Engagement'].mode()[0])

30.2
0.594
0.58
0    0.25
1    0.47
2    0.58
3    0.76
4    0.91
Name: Engagement, dtype: float64
0.25


In [11]:
# Exercise 6
media_types = [
    "YouTube", "Instagram", "Radio", "TikTok",
    "Email chain", "Facebook", "News site",
    "Discord", "Reddit", "Town crier"
]

print(media_types)

for media in media_types:
    print(media)


['YouTube', 'Instagram', 'Radio', 'TikTok', 'Email chain', 'Facebook', 'News site', 'Discord', 'Reddit', 'Town crier']
YouTube
Instagram
Radio
TikTok
Email chain
Facebook
News site
Discord
Reddit
Town crier


In [12]:
# Exercise 6 continued
for name in df['Name']:
    print(name)

Gizmo
Jamie
Morgan
Taylor
Jordan
